feat: allow different icon variants in ErrorMessage
ZopaPublic/react-components pull request #1137
Opened 2024-08-13 15:25 UTC by gbkr

2024-08-13 15:33 UTC, zopa-charlotte-walker approved these changes

2024-08-13 15:37 UTC, OlenaKashuba requested changes
can you push changeset plz `pnpm changeset` and commit the file created

2024-08-13 19:41 UTC, zopa-charlotte-walker approved these changes

2024-08-14 13:19 UTC, OlenaKashuba approved these changes

2024-08-14 13:28 UTC, merged